# Generated by Django 2.2 on 2021-09-09 06:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='model',
            options={'verbose_name_plural': 'Товары'},
        ),
    ]
