# Generated by Django 2.2 on 2021-09-09 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0003_category_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='model',
            name='price',
            field=models.SmallIntegerField(default='0'),
        ),
    ]
