# Generated by Django 2.2 on 2021-09-10 02:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('service', '0004_model_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='model',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Опубликовано'),
        ),
    ]
